__object__:
  path: depth_anything_3.model.da3
  name: DepthAnything3Net
  args: as_params

net:
  __object__:
    path: src.fusion_encoder
    name: FusionEncoder
    args: as_params

  name: vits
  out_layers: [5, 7, 9, 11]
  fusion_layers: [4]
  alt_start: 4
  qknorm_start: 4
  rope_start: 4
  cat_token: True

head:
  __object__:
    path: depth_anything_3.model.dualdpt
    name: DualDPT
    args: as_params

  dim_in: &head_dim_in 768
  output_dim: 2
  features: &head_features 64
  out_channels: &head_out_channels [48, 96, 192, 384]


cam_enc:
  __object__:
    path: depth_anything_3.model.cam_enc
    name: CameraEnc
    args: as_params

  dim_out: 384

cam_dec:
  __object__:
    path: depth_anything_3.model.cam_dec
    name: CameraDec
    args: as_params

  dim_in: 768

depth_tokenizer:
  __object__:
    path: src.depth_tokenizer
    name: depth_tokenizer
    args: as_params

  output_dim: 384
  model_type: 'Tiny'