__object__:
  path: src.recon3d
  name: MapGuidedRecon3D
  args: as_params

depth_tokenizer:
  __object__:
    path: src.depth_tokenizer
    name: depth_tokenizer
    args: as_params

  model_type: 'Small'  
  output_dim: 768

net:
  __object__:
    path: src.fusion_encoder
    name: FusionEncoder
    args: as_params

  name: vitb
  out_layers: [5, 7, 9, 11]
  fusion_layers: [4]
  alt_start: 4
  qknorm_start: 4
  rope_start: 4
  cat_token: True

head:
  __object__:
    path: depth_anything_3.model.dualdpt
    name: DualDPT
    args: as_params

  dim_in: &head_dim_in 1536
  output_dim: 2
  features: &head_features 128
  out_channels: &head_out_channels [96, 192, 384, 768]


cam_enc:
  __object__:
    path: depth_anything_3.model.cam_enc
    name: CameraEnc
    args: as_params

  dim_out: 768

cam_dec:
  __object__:
    path: depth_anything_3.model.cam_dec
    name: CameraDec
    args: as_params

  dim_in: 1536
